#!/bin/bash

mkdir -p mobilenet/plantnet
mkdir -p mobilenet/object_detection

wget "https://lab.plantnet.org/seafile/d/01ab6658dad6447c95ae/files/?p=%2Fmobilenet_v3_large_weights_best_acc.tar&dl=1" -O mobilenet/plantnet/mobilenet_v3_large_weights_best_acc.tar
wget "https://lab.plantnet.org/seafile/d/bed81bc15e8944969cf6/files/?p=%2Fclass_idx_to_species_id.json&dl=1" -O mobilenet/plantnet/class_idx_to_species_id.json
wget "https://lab.plantnet.org/seafile/d/bed81bc15e8944969cf6/files/?p=%2Fplantnet300K_metadata.json&dl=1" -O mobilenet/plantnet/plantnet300K_metadata.json
wget "https://lab.plantnet.org/seafile/d/bed81bc15e8944969cf6/files/?p=%2Fplantnet300K_species_id_2_name.json&dl=1" -O mobilenet/plantnet/plantnet300K_species_id_2_name.json

wget "https://raw.githubusercontent.com/chuanqi305/MobileNet-SSD/refs/heads/master/deploy.prototxt" -O mobilenet/object_detection/deploy.prototxt
wget "https://github.com/chuanqi305/MobileNet-SSD/raw/refs/heads/master/mobilenet_iter_73000.caffemodel" -O mobilenet/object_detection/mobilenet_iter_73000.caffemodel
